version: '3.7'

services:
  mini-api-node:
    container_name: sample-api-node
    build: ${SAMPLE_API_PATH:-.}/docker
    image: nexus.wako057.net:18442/sample-api-node:1.0
    volumes:
      - ${MINI_API_PATH:-.}/:/var/nodejs/sample-api-node
    expose:
      - 8080
    labels:
      traefik.frontend.rule: "Host: sample-api.wako057.net"
      traefik.docker.network: "front"
      traefik.port: 8080
      traefik.frontend.entryPoints: http
    environment:
      NODE_PORT: 8080
      NODE_ENV: development
      ENV_LOG_LEVEL: trace
      ENV_LOG_DISABLE_STATUS: 1
    networks:
      front:
